version: '3.8'

services:
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/seattle_reuse
      - STRIPE_SECRET_KEY=your_stripe_secret_key
      - RESEND_API_KEY=your_resend_api_key
      - TWILIO_AUTH_TOKEN=your_twilio_auth_token
      - MEILISEARCH_API_KEY=your_meilisearch_api_key
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: seattle_reuse
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./services/api/database/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped

  frontend:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8080
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data: